# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_feedback_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
